### ISSUE TITLE
发布对应的 npm 包

### ISSUE THREAD

**Issue by wxungang** [kayuanweb/Mock#2]

**Comment by cleverpp** [comment]
是指在npmjs.com中注册并重新发布一个包么？
还是将最新的mockjs代码放入node_modules?

**Comment by wxungang** [comment]
> 是指在npmjs.com中注册并重新发布一个包么？
> 还是将最新的mockjs代码放入node_modules?

npmjs 注册一个相关的组织，然后发布对应的 mockjs 版本供开放使用....

**Comment by wxungang** [comment]
kayuan-mockjs
